require "bundler/gem_tasks"

require 'rake/testtask'
require 'rake/clean'

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/**/test_*.rb']
  t.verbose = true
end

task :default => :test

module Bundler
  class GemHelper
    def release_gem
      guard_clean
      guard_already_tagged
      built_gem_path = build_gem
      tag_version {
        git_push
        geminabox_push(built_gem_path)
      }
    end

    def geminabox_push(path)
      sh("gem push '#{path}'")
      Bundler.ui.confirm "Pushed #{name} #{version} to gems.iseesmic.com"
    end
  end
end
